// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package extra

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/ansufw/go-mazer/apps/web/config"
	"github.com/ansufw/go-mazer/views/layouts"
)

func Avatar(sidebarItems []config.SidebarItem, filename string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = blockContent().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Home", "Go Mazer", sidebarItems, filename, nil, nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func blockContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-heading\"><div class=\"page-title\"><div class=\"row\"><div class=\"col-12 col-md-6 order-md-1 order-last\"><h3>Avatar</h3><p class=\"text-subtitle text-muted\">A container to show avatar images or initials.</p></div><div class=\"col-12 col-md-6 order-md-2 order-first\"><nav aria-label=\"breadcrumb\" class=\"breadcrumb-header float-start float-lg-end\"><ol class=\"breadcrumb\"><li class=\"breadcrumb-item\"><a href=\"index.html\">Dashboard</a></li><li class=\"breadcrumb-item active\" aria-current=\"page\">Avatar</li></ol></nav></div></div></div><section class=\"section\"><div class=\"card\"><div class=\"card-header\"><h4 class=\"card-title\">Default Avatar</h4></div><div class=\"card-body\"><p>Wrap your content with <code>.avatar</code> class and wrap your text in <code>.avatar-content</code> to create a avatar.You have to use inline attributes to set height width of image in default avatar.</p><div class=\"avatar bg-primary me-3\"><span class=\"avatar-content\"><i class=\"bi bi-envelope\"></i></span></div><div class=\"avatar bg-warning me-3\"><span class=\"avatar-content\">AS</span></div><div class=\"avatar bg-warning me-3\"><img src=\"assets/static/images/faces/1.jpg\" alt=\"\" srcset=\"\"></div></div></div></section><section class=\"section\"><div class=\"card\"><div class=\"card-header\"><h4 class=\"card-title\">Avatar Sizes</h4></div><div class=\"card-body\"><p>use class <code>.avatar-")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("{sm|lg|xl}")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/menu/extra/avatar.templ`, Line: 61, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</code> with <code>.avatar</code> to modify size of your avatar.</p><div class=\"avatar avatar-sm bg-primary me-3\"><span class=\"avatar-content\"><i class=\"bi bi-envelope\"></i></span></div><div class=\"avatar bg-warning me-3\"><span class=\"avatar-content\">AS</span></div><div class=\"avatar me-3\"><img src=\"assets/static/images/faces/1.jpg\" alt=\"\" srcset=\"\"></div><div class=\"avatar avatar-lg me-3\"><img src=\"assets/static/images/faces/2.jpg\" alt=\"\" srcset=\"\"></div><div class=\"avatar avatar-xl me-3\"><img src=\"assets/static/images/faces/3.jpg\" alt=\"\" srcset=\"\"></div></div></div></section><section class=\"section\"><div class=\"card\"><div class=\"card-header\"><h4 class=\"card-title\">Avatar Status</h4></div><div class=\"card-body\"><p>use class <code>.avatar-status</code> and <code>.bg-")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("{color}")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/menu/extra/avatar.templ`, Line: 87, Col: 81}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</code> after <code>.avatar-content</code></p><div class=\"avatar bg-warning me-3\"><span class=\"avatar-content\">AS</span> <span class=\"avatar-status bg-success\"></span></div><div class=\"avatar bg-warning me-3\"><img src=\"assets/static/images/faces/1.jpg\" alt=\"\" srcset=\"\"> <span class=\"avatar-status bg-danger\"></span></div></div></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
